# frozen_string_literal: true

require_relative 'enhancements/route_concerns'

require_relative 'enhancements/actionable/model'
require_relative 'enhancements/actionable/serializer'
require_relative 'enhancements/creatable/action'
require_relative 'enhancements/creatable/controller'
require_relative 'enhancements/destroyable/action'
require_relative 'enhancements/destroyable/controller'
require_relative 'enhancements/destroyable/routing'
require_relative 'enhancements/indexable/model'
require_relative 'enhancements/menuable/model'
require_relative 'enhancements/menuable/serializer'
require_relative 'enhancements/singularable/controller'
require_relative 'enhancements/singularable/model'
require_relative 'enhancements/singularable/serializer'
require_relative 'enhancements/tableable/model'
require_relative 'enhancements/updatable/action'
require_relative 'enhancements/updatable/controller'
require_relative 'enhancements/updatable/routing'
require_relative 'enhancements/updatable/serializer'
