name: Ruby Gem

on:
  push:
    tags:
      - v*

jobs:
  publish_rubygems:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build release
        uses: cadwallion/publish-rubygems-action@master
        env:
          PUBLISH_PRERELEASE: true
          RELEASE_COMMAND: rake build

      - name: Publish Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          PUBLISH_PRERELEASE: true
          RELEASE_COMMAND: rake release:rubygem_push

  publish_gh_packages:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
